name: Community Extension Build
on:
  pull_request:
  push:

jobs:
  prepare:
    outputs:
      COMMUNITY_EXTENSION_NAME: ${{ steps.parse.outputs.COMMUNITY_EXTENSION_NAME }}
      COMMUNITY_EXTENSION_GITHUB: ${{ steps.parse.outputs.COMMUNITY_EXTENSION_GITHUB }}
      COMMUNITY_EXTENSION_REF: ${{ steps.parse.outputs.COMMUNITY_EXTENSION_REF }}
      COMMUNITY_EXTENSION_DEPLOY: ${{ steps.parse.outputs.COMMUNITY_EXTENSION_DEPLOY }}
      COMMUNITY_EXTENSION_EXCLUDE_PLATFORMS: ${{ steps.parse.outputs.COMMUNITY_EXTENSION_EXCLUDE_PLATFORMS }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get all changed description files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          extensions/*/description.yml

    - name: Parse description files
      id: parse
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        pip install pyyaml
        python scripts/build.py
        cat env.sh >> $GITHUB_OUTPUT
        echo `cat $GITHUB_OUTPUT`

  build:
    needs: prepare
    uses: samansmink/extension-ci-tools/.github/workflows/_extension_distribution.yml@add-support-for-community-extensions
    if: ${{ needs.prepare.outputs.COMMUNITY_EXTENSION_NAME != '' }}
    with:
      duckdb_version: v1.0.0
      enable_rust: true
      exclude_archs: ${{ needs.prepare.outputs.COMMUNITY_EXTENSION_EXCLUDE_PLATFORMS }}
      extension_name: ${{ needs.prepare.outputs.COMMUNITY_EXTENSION_NAME }}
      override_repository: ${{ needs.prepare.outputs.COMMUNITY_EXTENSION_GITHUB }}
      override_ref: ${{ needs.prepare.outputs.COMMUNITY_EXTENSION_REF }}

  deploy:
    needs: 
      - prepare
      - build
    uses: samansmink/extension-ci-tools/.github/workflows/_extension_deploy.yml@add-support-for-community-extensions
    if: ${{ needs.prepare.outputs.COMMUNITY_EXTENSION_DEPLOY != '' }}
    secrets: inherit
    with:
      deploy_latest: true
      duckdb_version: v1.0.0
      exclude_archs: ${{ needs.prepare.outputs.COMMUNITY_EXTENSION_EXCLUDE_PLATFORMS }}
      extension_name: ${{ needs.prepare.outputs.COMMUNITY_EXTENSION_NAME }}
      override_repository: ${{ needs.prepare.outputs.COMMUNITY_EXTENSION_GITHUB }}
      override_ref: ${{ needs.prepare.outputs.COMMUNITY_EXTENSION_REF }}
      core_nightly_deploy: false
      community_deploy: true