name: Community Extension Deploy
on:
  workflow_dispatch

jobs:
  prepare:
    name: Find extensions to deploy
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: set-matrix
        run: |
          pip install pyyaml
          echo "{"include": [" >> matrix.json
          for FILE in extensions/*/description.yml; do
            ALL_CHANGED_FILES=$FILE python scripts/build.py
            source env.sh
            echo "{\"COMMUNITY_EXTENSION_NAME\" : \"$COMMUNITY_EXTENSION_NAME\",\"COMMUNITY_EXTENSION_GITHUB\" : \"$COMMUNITY_EXTENSION_GITHUB\",\"COMMUNITY_EXTENSION_REF\" : \"$COMMUNITY_EXTENSION_REF\"}", >> matrix.json
          done
          echo "]}" >> matrix.json

          matrix="`cat matrix.json`"
          echo matrix=$matrix >> $GITHUB_OUTPUT
          echo `cat $GITHUB_OUTPUT`

  build:
    needs: prepare
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.0.0
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    with:
      duckdb_version: v1.0.0
      extension_name: ${{ matrix.COMMUNITY_EXTENSION_NAME }}
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools'
      repository: ${{ matrix.COMMUNITY_EXTENSION_GITHUB }}
      ref: ${{ matrix.COMMUNITY_EXTENSION_REF }}

  deploy:
    needs: 
      - prepare
      - build
    uses: ./.github/workflows/_extension_deploy.yml
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    secrets: inherit
    with:
      deploy_latest: true
      duckdb_version: v1.0.0
      extension_name: ${{ matrix.COMMUNITY_EXTENSION_NAME }}
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools'
      repository: ${{ matrix.COMMUNITY_EXTENSION_GITHUB }}
      ref: ${{ matrix.COMMUNITY_EXTENSION_REF }}


